### ISSUE TITLE
crash due to Siema instance doesn't have`removeAllListeners()`

### ISSUE THREAD

**Issue by passerbyid** [lexzhukov/ngx-siema#18]
in `ngx-siema.component.ts`:
```javascript
ngOnDestroy() {
   this.instance.removeAllListeners();
   this.instance.destroy();
   this.instance = null;
 }
```
When component is on destroy, call `this.instance.removeAllListeners()` will crash the app due to Siema instance doesn't have`removeAllListeners()`.

I don't know where is `removeAllListeners()` defined and what is it's purpose, but if remove this line, everything looks fine to me.

**Comment by lexzhukov** [comment]
@passerbyid thanks for your bug report. I will review your PR.

**Comment by lexzhukov** [comment]
The bug is fixed in https://github.com/lexzhukov/ngx-siema/commit/09885cc143c3a09d9f42c4011a39bbaf1d9ccbcd. Today I will publish an updated package.

**Comment by vlyamzin** [comment]
@lexzhukov Looks like the issue is still present. For me it occurs on every route change.

Here is the [plunker](https://plnkr.co/edit/QvbdRjbjmsJwB68yOwQy?p=preview)

**Comment by cg50x** [comment]
@lexzhukov Seeing this issue as well. I've looked at the code in siema js. It looks like removing the call to `removeAllListeners()` should fix it.

**Comment by omobono** [comment]
Me too.

**Comment by Justinemmerich** [comment]
Please fix this error asap, thx
